## AVALIAÇÃO COM NOTA

Tarefera final realizada durante o curso **Bancos de dados e SQL para ciência de dados com Python**, realizado através plataforma **Coursera**, visando avaliar as habilidades no uso de banco de dados SQLite com python.

## Compreendendo os conjuntos de dados

Para resolver os problemas propostos, foram utilizados três conjuntos de dados disponíveis no Portal de Dados da cidade de Chicago:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>

2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>

3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Indicadores socioeconômicos em Chicago

Este conjunto de dados contém uma seleção de seis indicadores socioeconômicos relevantes para a saúde pública e um “índice de vulnerabilidade” para cada área comunitária de Chicago, referentes aos anos de 2008 a 2012.

### 2. Escolas Públicas de Chicago

Este conjunto de dados apresenta todos os dados de desempenho por escola utilizados para elaborar os Boletins Escolares do CPS (Escolas Públicas de Chicago) para o ano letivo de 2011-2012.

### 3. Dados sobre criminalidade em Chicago

Este conjunto de dados reflete os incidentes criminais registrados (com exceção dos homicídios, para os quais existem dados individuais por vítima) ocorridos na cidade de Chicago de 2001 até o presente, excluindo os últimos sete dias.

#### Instalando e importando as bibliotecas necessárias

In [ ]:
!pip install pandas
!pip install ipython-sql prettytable 

import prettytable
prettytable.DEFAULT = 'DEFAULT'

import csv
import sqlite3
import pandas as pd

### Armazenando os datasets em tabelas de banco de dados

Primeiro vamos carregá-los no banco de dados SQLite.
Criaremos três tabelas, conforme descrito a seguir:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

##### Estabelecendo uma conexão com o arquivo FinalDB.db e carregando o módulo SQL magic

In [2]:
con = sqlite3.connect("FinalDB.db")
cur = con.cursor()
%reload_ext sql

##### Usando pandas o **`Pandas`** para carregar os dados disponíveis nos links acima em dataframes.

In [3]:
census_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01"
cps_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01"
ccd_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01"

df1 = pd.read_csv(census_url)
df1.to_sql("CENSUS_DATA", con, if_exists='replace', index=False)
df2 = pd.read_csv(cps_url)
df2.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists='replace', index=False)
df3 = pd.read_csv(ccd_url)
df3.to_sql("CHICAGO_CRIME_DATA", con, if_exists='replace', index=False,)

533

##### Estabelecendo a conexão entre o módulo `SQL Magic` e o banco de dados `FinalDB.db`.

In [4]:
%sql sqlite:///FinalDB.db

##### Exibindo as 5 primeiras linhas do DataFrame 3 — `CHICAGO_CRIME_DATA`.

In [5]:
df3.head()

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"

### Problema 1:
##### Descubrir o número total de crimes registrados na tabela CRIME.

In [6]:
%sql SELECT count(ID) from CHICAGO_CRIME_DATA;

 * sqlite:///FinalDB.db
Done.

[(533,)]

### Problem 2:
##### Listar os nomes e números das áreas comunitárias com renda per capita inferior a 11.000.

In [7]:
%%sql SELECT COMMUNITY_AREA_NAME, COMMUNITY_AREA_NUMBER
FROM CENSUS_DATA WHERE 	PER_CAPITA_INCOME < 11000;

 * sqlite:///FinalDB.db
Done.

[('West Garfield Park', 26.0),
 ('South Lawndale', 30.0),
 ('Fuller Park', 37.0),
 ('Riverdale', 54.0)]

### Problema 3

##### Listar todos os números de casos relativos a crimes envolvendo menores? (As crianças não são consideradas menores para fins de análise criminal).

In [8]:
%%sql SELECT * FROM CHICAGO_CRIME_DATA 
    WHERE DESCRIPTION LIKE '%minor%';

 * sqlite:///FinalDB.db
Done.

[(3987219, 'HL266884', '2005-03-31', '024XX N CLARK ST', '2210', 'LIQUOR LAW VIOLATION', 'SELL/GIVE/DEL LIQUOR TO MINOR', 'CONVENIENCE STORE', 1, 0, 2333, 19, 43.0, 7.0, '22', 1172680.0, 1916483.0, 2005, 41.92626872, -87.64089934, '(41.926268719, -87.640899336)'),
 (3266814, 'HK238408', '2004-03-13', '093XX S STONY ISLAND AVE', '2230', 'LIQUOR LAW VIOLATION', 'ILLEGAL CONSUMPTION BY MINOR', 'ALLEY', 1, 0, 413, 4, 8.0, 48.0, '22', 1188539.0, 1843379.0, 2004, 41.72530099, -87.58496589, '(41.72530099, -87.584965887)')]

## Problem 4

##### Enumerar todos os crimes de sequestro envolvendo crianças.

In [9]:
%%sql select * from chicago_crime_data
where primary_type = 'KIDNAPPING' and description like '%child%';

 * sqlite:///FinalDB.db
Done.

[(5276766, 'HN144152', '2007-01-26', '050XX W VAN BUREN ST', '1792', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER', 'STREET', 0, 0, 1533, 15, 29.0, 25.0, '20', 1143050.0, 1897546.0, 2007, 41.87490841, -87.75024931, '(41.874908413, -87.750249307)')]

### Problema 5

##### Listar os tipos de crimes registrados nas escolas. (Sem repetições)

In [28]:
%%sql select distinct primary_type from chicago_crime_data
where location_description like '%school%';

 * sqlite:///FinalDB.db
Done.

[('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('ASSAULT',),
 ('CRIMINAL TRESPASS',),
 ('PUBLIC PEACE VIOLATION',)]

### Problema 6

##### Listar os tipos de escolas, juntamente com a média de segurança de cada tipo.

In [17]:
%%sql select "Elementary, Middle, or High School", AVG(safety_score) AS "AVG_Safety_Score"
from CHICAGO_PUBLIC_SCHOOLS
group by "Elementary, Middle, or High School";

 * sqlite:///FinalDB.db
(sqlite3.OperationalError) near "or": syntax error
[SQL: select Elementary, Middle, or High School , AVG(safety_score) AS AVG_Safety_Score
from CHICAGO_PUBLIC_SCHOOLS
group by "Elementary, Middle, or High School";]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [23]:
# Solução alternativa devido problemas da extensão ipython-sql com nomes de colunas que contém vígulas.
query = '''
SELECT "Elementary, Middle, or High School", AVG(safety_score) AS "AVG_Safety_Score"
FROM CHICAGO_PUBLIC_SCHOOLS
GROUP BY "Elementary, Middle, or High School"
'''
df = pd.read_sql_query(query, con)
df.head()

  Elementary, Middle, or High School  AVG_Safety_Score
0                                 ES         49.520384
1                                 HS         49.623529
2                                 MS         48.000000

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [24]:
%%sql select community_area_name from Census_data
order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc
limit 5;

 * sqlite:///FinalDB.db
Done.

[('Riverdale',),
 ('Fuller Park',),
 ('Englewood',),
 ('North Lawndale',),
 ('East Garfield Park',)]

### Problema 8

##### Qual área comunitária é mais propensa ao crime? Indique apenas o número da área comunitária.

In [25]:
%%sql SELECT COMMUNITY_AREA_NUMBER
FROM CHICAGO_CRIME_DATA
WHERE COMMUNITY_AREA_NUMBER IS NOT NULL
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(*) DESC
    limit 1;

 * sqlite:///FinalDB.db
Done.

[(25.0,)]

### Problema 9

##### Use uma subconsulta para encontrar o nome da área comunitária com o maior índice de vulnerabilidade.

In [26]:
%%sql select community_area_name from Census_data
where hardship_index IN (select max(hardship_index) from Census_data);

 * sqlite:///FinalDB.db
Done.

[('Riverdale',)]

### Problema 10

##### Use uma subconsulta para determinar o nome da área comunitária com o maior número de crimes.

In [29]:
%%sql SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = 
    (SELECT COMMUNITY_AREA_NUMBER FROM CHICAGO_CRIME_DATA
    WHERE COMMUNITY_AREA_NUMBER IS NOT NULL
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 1);

 * sqlite:///FinalDB.db
Done.

[('Austin',)]